# create zmq network for sending the data and having it mounted
# through the docker-compose file
version: '3'

services:
  # building zmq server that transfers data from csv to python-analyze-gait
  zmq-server:
    image:
      - pwalsh4/zmqserver
    build:
      context: .
      dockerfile: docker/zmq_server.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 5555:5555
  gait-analysis:
    image:
      - pwalsh4/gaitvisualization
    build:
      context: .
      dockerfile: docker/analyze_gait.Dockerfile
      environment:
        - DISPLAY=${DISPLAY}
      network_mode: host
    volumes:
      - ./:/usr/src/app
      - /tmp/.X11-unix:/tmp/.X11-unix

