# create zmq network for sending the data and having it mounted
# through the docker-compose file
version: "3"

services:
  # building zmq server that transfers data from csv to python-analyze-gait
  zmqserver:
    build:
      context: .
      dockerfile: docker/zmq_server.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "5555:5555"
    depends_on:
      - "gait-analysis"
    environment:
      - ZMQ_SERVER_IP=192.168.92.22
      - ZMQ_SERVER_PORT=5555
    networks:
      zmq-network:
        ipv4_address: "192.168.92.22"
  gait-analysis:
    build:
      context: .
      dockerfile: docker/analyze_gait.Dockerfile
    environment:
      - ZMQ_SERVER_IP=192.168.92.22
      - ZMQ_SERVER_PORT=5555
      - DISPLAY=$DISPLAY
    volumes:
      - ./:/usr/src/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:rw
    networks:
      zmq-network:
        ipv4_address: "192.168.92.21"
networks:
  zmq-network:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"
