# create zmq network for sending the data and having it mounted
# through the docker-compose file
version: "3"

services:
  # building zmq server that transfers data from csv to python-analyze-gait
  zmqserver:
    # image:
    #   - "pwalsh4/zmqserver"
    build:
      context: .
      dockerfile: docker/zmq_server.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "5555:5555"
    depends_on:
      - "gait-analysis"
  gait-analysis:
    # image:
    #   - "pwalsh4/gait_visualization:latest"
    build:
      context: .
      dockerfile: docker/analyze_gait.Dockerfile
    # network_mode: "host"
    volumes:
      - ./:/usr/src/app
      - $HOME/.Xauthority:/root/.Xauthority:rw
    links:
      - "zmqserver"
