# create zmq network for sending the data and having it mounted
# through the docker-compose file
version: "3"

services:
  # building zmq server that transfers data from csv to python-analyze-gait
  zmqserver:
    build:
      context: .
      dockerfile: docker/analyze_gait.Dockerfile
    volumes:
      - ./:/app
    ports:
      - "5555:5555"
    depends_on:
      - "gait-analysis"
    environment:
      - ZMQ_SERVER_IP=192.168.92.22
      - ZMQ_SERVER_PORT=5555
    working_dir: /app/src
    networks:
      zmq-network:
        ipv4_address: "192.168.92.22"
    command: poetry run python -m zmq_server 192.168.92.22 5555
  gait-analysis:
    build:
      context: .
      dockerfile: docker/analyze_gait.Dockerfile
    environment:
      - ZMQ_SERVER_IP=192.168.92.22
      - ZMQ_SERVER_PORT=5555
      - DISPLAY=host.docker.internal:0
    volumes:
      - ./:/app
      # - /tmp/.X11-unix:/tmp/.X11-unix
      # - $HOME/.Xauthority:/root/.Xauthority:rw
    working_dir: /app/src
    networks:
      zmq-network:
        ipv4_address: "192.168.92.21"
    command: poetry run python -m analyze_gait 192.168.92.22 5555
networks:
  zmq-network:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"
